// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hugmdukusogzzqouceub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh1Z21kdWt1c29nenpxb3VjZXViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwODc0NTMsImV4cCI6MjA3MjY2MzQ1M30.Sw0qrkhzGo535Dg5RlWCQlwUk7ZQ3_ne3yC7SIJRkYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});